services:
  # Development Frontend Service (with hot reload)
  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Development Backend Service (with auto-reload)
  api:
    environment:
      - DEBUG=true
      - RELOAD_ON_CHANGE=true
    volumes:
      - ../backend:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
